name: mtusiapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ## Flutter SDK
  flutter:
    sdk: flutter

  ## Online
  web_socket_channel: ^1.1.0
  dio: ^4.0.0


  ## Widgets
  grouped_list: ^4.0.0
  photo_view: ^0.11.1
  animated_theme_switcher: ^1.0.6
  cached_network_image: ^2.5.1
  flutter_markdown: ^0.6.0
  shimmer: ^1.1.2
  scrollable_positioned_list: ^0.1.9
  flutter_inner_drawer: ^0.5.7+2
  mask_text_input_formatter: ^1.2.1
  auto_size_text: ^2.1.0
  percent_indicator: ^3.0.1
  search_page: ^2.0.0
  big_tip: ^2.0.0
  expandable:
    git:
      url: git://github.com/KhalillHussein/flutter-expandable.git


  ## Tools
  provider: ^4.1.3+1
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  intl: ^0.16.1
  path: ^1.6.4
  lint: ^1.5.3
  flutter_statusbarcolor: ^0.2.3
  flutter_local_notifications: ^1.4.4+4
  flutter_web_browser: ^0.14.0
  url_launcher: ^6.0.3
  equatable: ^2.0.0
  google_fonts: ^2.0.0

  ## Icons
  material_design_icons_flutter: ^4.0.5855
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
   - assets/images/

  uses-material-design: true



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
