name: mtusiapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.9.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ## Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ## Online
  dio: ^4.0.0


  ## Widgets
  grouped_list: ^4.0.0
  photo_view: ^0.11.1
  animated_theme_switcher: ^1.0.9
  cached_network_image: ^3.0.0
  flutter_markdown: ^0.6.1
  shimmer: ^2.0.0
  scrollable_positioned_list: ^0.1.10
  auto_size_text: ^2.1.0
  percent_indicator: ^3.0.1
  search_page: ^2.0.0
  big_tip: ^2.0.0
  table_calendar: ^3.0.0
  row_collection: ^0.2.5
  row_item: ^2.0.0
  expand_widget: ^2.0.0
  markdown_editable_textinput: ^2.0.0
  datetime_picker_formfield: ^2.0.0
  dotted_border: ^2.0.0
  expandable:
    git:
      url: git://github.com/KhalillHussein/flutter-expandable.git


  ## Tools
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  path: ^1.8.0
  lint: ^1.5.3
  flutter_statusbarcolor: ^0.2.3
  flutter_web_browser: ^0.14.0
  url_launcher: ^6.0.3
  image_picker: ^0.7.4
  google_fonts: ^2.0.0
  share: ^2.0.1
  app_settings: ^4.1.0
  quick_actions: ^0.6.0+1
  path_provider: ^2.0.1
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0

  ## Icons
  material_design_icons_flutter: ^4.0.5955
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  image_path: assets/images/app_icon.png
  remove_alpha_ios: true
  android: false
  ios: true

flutter_native_splash:
  image: assets/images/logo_splash_dark.png
  color: "#121212"

#  color_dark: "#1D1D1D"
#  image_dark: assets/images/logo_splash_dark.png
#  android: true
#  ios: true

flutter:

  assets:
   - assets/images/

  uses-material-design: true



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
